### ISSUE TITLE
Compass shuffled error

### ISSUE THREAD

**Issue by lurch9229** [matthewkirby/plando-random-settings#6]
Not sure if this an issue for you or Roman, but tried genning a seed and kept getting error when the generator was trying to place compasses in locations other than dungeons when it JSON had set it to dungeons only.

This must have come from one of the recent updated made to Romans branch of the rando settings Branch, as it was fine before I updated to these versions (beans beans + 5.2.65 R-9)

**Comment by matthewkirby** [comment]
Hey, so you need to have updated version of Romans branch and the script or you will run into errors. If the generator is failing, when placing items, it is more likely something wrong in the randomizer rather than this script (if the generator fails immediatly the script could be the culprit).

Either way, can you post the plando file that is causing problems?

**Comment by lurch9229** [comment]
I updated Romans and this branch at the same time. I have a feeling it's more a problem with the new options added to shuffles with keys and maps+compass being able to put specifically in dungeons or overworld. I'll attach the Plando file, but at this point I think its more a problem for Roman, or Dev (not sure which added the new shuffle locations)

Looking over this Plando file it might also have a problem with it being no logic, but I just play these seeds so dont know much about troubleshooting

**Comment by lurch9229** [comment]
[blind_random_settings.zip](https://github.com/matthewkirby/plando-random-settings/files/5388486/blind_random_settings.zip)
